apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-label
  labels:
    app.kubernetes.io/name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: registry.digitalocean.com/kubiclayer/nginx:alpine
          ports:
            - containerPort: 80